In [1]:
import pandas as pd

In [ ]:
# data frame = exsel shit = database table=zbir od poveke serii
# serie =colum = nunmy array

In [7]:
broevi = pd.Series( [1,2,3,4,5,6, "Skopje", "ohrid"])
print (broevi)

0         1
1         2
2         3
3         4
4         5
5         6
6    Skopje
7     ohrid
dtype: object

In [10]:
# fali, od lista, od dictionary, od baza na podatoci
lista_podatoci = [
    {"grad": "Skopje", "temperatura": 35},
    {"grad": "Shtip", "temperatura": 30}
   ]

dp = pd.DataFrame(lista_podatoci)

print(dp)

     grad  temperatura
0  Skopje           35
1   Shtip           30

In [9]:
import pandas as pd
df_csv=pd.read_csv("orders_data.csv",usecols=["Product","Quantity","Total_Amount"])
df_csv

       Product  Quantity  Total_Amount
0     Keyboard         5       4203.42
1   Smartphone         3       9347.40
2       Laptop         3       1161.79
3      Monitor         1       4389.90
4        Mouse         5       5366.67
..         ...       ...           ...
95     Monitor         2       9360.70
96       Mouse         1       7703.43
97      Tablet         1        536.12
98  Smartphone         4       7493.87
99  Smartphone         4       3090.85

[100 rows x 3 columns]

In [10]:
df_json=pd.read_json("posledni_redovi.json")
df_json

   Order_ID  Customer_ID  Order_Date     Product  Quantity  Total_Amount
0        93           14  2024-01-12      Laptop         5       4182.99
1        94           49  2024-07-11     Monitor         2       3201.00
2        95           19  2024-07-03       Mouse         1       4417.85
3        96           25  2024-10-02     Monitor         2       9360.70
4        97           30  2024-04-15       Mouse         1       7703.43
5        98           19  2024-08-31      Tablet         1        536.12
6        99           23  2024-01-11  Smartphone         4       7493.87
7       100           38  2024-06-20  Smartphone         4       3090.85

In [15]:
df_exsel=pd.read_excel("Forecast_Sales_Dataset.xlsx",sheet_name="Sheet1")
df_exsel

        Month  Monthly Sales (MKD)
0  2021-01-31             11323.88
1  2021-02-28             16376.57
2  2021-03-31             15118.32
3  2021-04-30             13296.47
4  2021-05-31             15704.20
5  2021-06-30             12677.61
6  2021-07-31             12370.28
7  2021-08-31              9736.22
8  2021-09-30              8731.61
9  2021-10-31              8940.44
10 2021-11-30              9613.68
11 2021-12-31             11269.33
12 2022-01-31             11560.21
13 2022-02-28             13027.67
14 2022-03-31             15183.27
15 2022-04-30             13491.43
16 2022-05-31             14895.06
17 2022-06-30             15104.73
18 2022-07-31             11540.62
19 2022-08-31              9206.65
20 2022-09-30              7852.33
21 2022-10-31              7865.17
22 2022-11-30              9991.94
23 2022-12-31             11919.95
24 2023-01-31             13863.42
25 2023-02-28             15949.98
26 2023-03-31             16506.41
27 2023-04-30             15381.54
28 2023-05-31             14104.71
29 2023-06-30             13594.77
30 2023-07-31             11012.16
31 2023-08-31              8516.63
32 2023-09-30             10439.39
33 2023-10-31              8184.79
34 2023-11-30             11573.05
35 2023-12-31             12841.64

In [ ]:
df_exsel.head(3)  #kolku redovi sakame da videme od pochetok

       Month  Monthly Sales (MKD)
0 2021-01-31             11323.88
1 2021-02-28             16376.57
2 2021-03-31             15118.32

In [ ]:
df_exsel.tail(10)   # kolku redovi sakame da videme od krajot

        Month  Monthly Sales (MKD)
26 2023-03-31             16506.41
27 2023-04-30             15381.54
28 2023-05-31             14104.71
29 2023-06-30             13594.77
30 2023-07-31             11012.16
31 2023-08-31              8516.63
32 2023-09-30             10439.39
33 2023-10-31              8184.79
34 2023-11-30             11573.05
35 2023-12-31             12841.64

In [19]:
df_exsel.to_csv("nov fajl od pandas.csv",index=False)
df_exsel.to_excel("nov fajl od pandas.xlsx",index=False)
df_exsel.to_json("nov fajl pd pandas.json",indent=False)

C:\Users\User\AppData\Local\Temp\ipykernel_63508\2068059407.py:3: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df_exsel.to_json("nov fajl pd pandas.json",indent=False)